config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :articles
  resources :homes
  get "", to: "homes#index", as: :root
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :related_products
  has_many :products, through: :related_products
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :related_products
  has_many :articles, through: :related_products
end

app/models/related_product.rb
class RelatedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :title, :description)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  helper_method :articles

  def index
    if params[:option].present?
      @products = Product.where(age_range: params[:option])
    else
      @products = Product.all
    end
  end

  def articles
    @articles = Article.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.fetch(:product, {})
    end
end

app/controllers/related_products_controller.rb
class RelatedProductsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
<div class="container-fluid mb-5 p-5 text-center shadow">
  <h1>Regala Mejor</h1>
  <h5 class="mt-4 fst-italic">Encuentra el mejor regalos</h5>
  <%= render('shared/searchbar') %>
</div>
<div class="container px-5 w-75">
    <h3 class="h5"><%= "TODOS LOS PUBLICOS" if params[:option] == "1" %></h3>
    <h3 class="h5"><%= "NIÑOS" if params[:option] == "2" %></h3>
    <h3 class="h5"><%= "ADULTOS" if params[:option] == "3" %></h3>
  <div class="row mt-5">
    <h3 class="h5">Recomendados</h3>
    <% @products.each do |product| %>
      <div class="col-4">
        <div class="card p-5">
          <h2 class="h3"><%= product.name %></h2>
          <h3 class="small"><%= product.age_range %></h2>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <% articles.first(2).each do |article| %>
      <div class="col-6">
        <div class="card p-5 h-100">
          <h2 class="h3"><%= article.title %></h2>
          <p><%= article.description %></p>
          <ul>
            <% article.products.each do |product| %>
              <li>
                <%= product.name %> <%= product.age %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render('shared/footer') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterGift2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
<%= link_to 'New Article', new_article_path %>

app/views/layouts/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/layouts/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/shared/_footer.html.erb
<footer class="text-center text-lg-start mt-5 shadow">
  <!-- Copyright -->
  <div class="text-center p-3">
    © 2024 Copyright:
    <a class="text-dark">RegalaMejor.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_searchbar.html.erb
<%= form_tag homes_path, method: :get do %>
  <div class="main-search-bar rounded-pill bg-white d-flex mx-auto mt-1 mb-5 w-50">
      <%= select_tag(:option, options_for_select([["Todos los públicos",1],["Niños",2],["Adultos",3]], params[:option] ), class:"flex-grow-1 d-flex align-items-center select") %>
    <%= submit_tag "Search", class: "btn btn-primary rounded-pill border-white border-5 px-3" %>
    </button>
  </div>
<% end %>